const trajlonEvents = [
    {
        id: 1,
        related_id: 19,
        imgSrc: "/asset/effectiveimg.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "23",
        monthYear: "June, 2026",
        location: "Sandton, South Africa",
        startTime: "23",
        endTime: "27 June 2026",
        participants: "150",
        regEndDate: "18/06/2026",
        skillLevel: "Procurement Management",
        title: "Effective Specifications Writing",
        slug: "effective-specifications-writing",
        seo: {
            seoTitle: "Effective Specifications Writing Workshop | Procurement Event | SkillHub International",
            seoDescription: "Join the Effective Specifications Writing event in Sandton, South Africa. Enhance your procurement management skills with expert-led sessions on writing clear and effective specifications. Register now for this essential procurement event!",
            seoKeywords: "specifications writing workshop, procurement event South Africa, operations training, procurement management, Sandton events, Trajlon Group events",
            seoHeading: "Effective Specifications Writing: Procurement Management Workshop",
        },
    },
    {
        id: 2,
        related_id: 17,
        imgSrc: "/asset/aiAndDataimg.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "14",
        monthYear: "July, 2026",
        location: "Cape Town, South Africa",
        startTime: "14",
        endTime: "18 July 2026",
        participants: "150",
        regEndDate: "08/07/2026",
        skillLevel: "Procurement Management",
        title: "Combatting procurement Fraud",
        slug: "combatting-procurement-fraud",
        seo: {
            seoTitle: "Combatting Procurement Fraud Seminar | Procurement Event | SkillHub International",
            seoDescription: "Attend the Combatting Procurement Fraud seminar in Cape Town. Learn best practices and strategies to prevent and detect procurement fraud in your organization. Secure your spot at this vital procurement management event.",
            seoKeywords: "procurement fraud seminar, operations fraud prevention, procurement management event, Cape Town events, Trajlon Group events, anti-fraud training",
            seoHeading: "Combatting Procurement Fraud: Procurement Risk Management",
        },
    },
    {
        id: 3,
        related_id: 30,
        imgSrc: "/asset/supervisoryimg.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "18",
        monthYear: "August, 2026",
        location: "Sandton, South Africa",
        startTime: "18",
        endTime: "22 August 2026",
        participants: "150",
        regEndDate: "15/08/2026",
        skillLevel: "Procurement Management",
        title: "Advanced Supervisory Management Skills",
        slug: "advanced-supervisory-management-skills",
        seo: {
            seoTitle: "Advanced Supervisory Management Skills Training | SkillHub International",
            seoDescription: "Join our Advanced Supervisory Management Skills training in Sandton. Enhance your leadership and management capabilities in procurement. Register now for this essential workshop!",
            seoKeywords: "supervisory management training, procurement leadership skills, operations management, Sandton events, Trajlon Group training",
            seoHeading: "Advanced Supervisory Management Skills: Leadership Training",
        },
    },
    {
        id: 4,
        related_id: 4,
        imgSrc: "/asset/effectiveimg.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "15",
        monthYear: "September, 2026",
        location: "Durban, South Africa",
        startTime: "15",
        endTime: "19 September 2026",
        participants: "150",
        regEndDate: "09/09/2026",
        skillLevel: "Ports & Shipping Management",
        title: "Advanced Principles in Ports and Marine Terminals Management",
        slug: "advanced-principles-in-ports-and-marine-terminals-management",
        seo: {
            seoTitle: "Advanced Principles in Ports and Marine Terminals Management | SkillHub International",
            seoDescription: "Enhance your expertise in ports and marine terminals management at our advanced training in Durban. Learn best practices and strategies for effective port operations. Register today!",
            seoKeywords: "ports management training, marine terminals management, logistics, Durban events, Trajlon Group training",
            seoHeading: "Advanced Principles in Ports and Marine Terminals Management",
        },
    },
    {
        id: 5,
        related_id: 31,
        imgSrc: "/asset/aiAndDataimg.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "20",
        monthYear: "October, 2026",
        location: "Dubai, AUE",
        startTime: "20",
        endTime: "24 October 2026",
        participants: "150",
        regEndDate: "22/09/2026",
        skillLevel: "Procurement Management",
        title: "AI and Data Analytics in Operations & International Conference on Global Logistics",
        slug: "ai-and-data-analytics-in-scm-international-conference-on-global-supply-chain-and-logistics",
        seo: {
            seoTitle: "AI and Data Analytics in Operations | Global Logistics Conference | SkillHub International",
            seoDescription: "Join the AI and Data Analytics in Operations conference in Dubai. Explore the latest trends and innovations in global logistics and operations. Network with industry leaders and enhance your knowledge.",
            seoKeywords: "AI in operations, data analytics conference, global logistics, Dubai events, Trajlon Group conference",
            seoHeading: "AI and Data Analytics in Operations: Global Logistics Conference",
        },
    },
    {
        id: 6,
        related_id: 15,
        imgSrc: "/asset/advancedimg.webp",
        youtubeUrl: "https://www.youtube.com/embed/C-EHoNfkoDM?si=ZGXNX6GSFRYTJ89W",
        dayDate: "17",
        monthYear: "November, 2026",
        location: "Sandton, South Africa",
        startTime: "17",
        endTime: "21 November 2026",
        participants: "150",
        regEndDate: "16/11/2026",
        skillLevel: "Transport and Distribution Management",
        title: "Transport and Fleet Management",
        slug: "transport-and-fleet-management",
        seo: {
            seoTitle: "Transport and Fleet Management Training | SkillHub International",
            seoDescription: "Enhance your transport and fleet management skills at our training in Sandton. Learn effective strategies for managing transportation and logistics operations. Register now!",
            seoKeywords: "transport management training, fleet management skills, logistics, Sandton events, Trajlon Group training",
            seoHeading: "Transport and Fleet Management: Logistics Training",
        },
    },
]

export default trajlonEvents;